[package]
name = "music-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = { version = "1.8.2" }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
symphonia = { version = "0.5.4", features = ["all"] }
thiserror = "2.0.12"
tracing = "0.1.41"
